### ISSUE TITLE
`XDG_CACHE_HOME` fallback missing

### ISSUE THREAD

**Issue by juliangruber** [filecoin-project/filecoin-station#107]
Currently you can't launch the app on linux if `$XDG_CACHE_HOME` isn't set.

> $XDG_CACHE_HOME defines the base directory relative to which user-specific non-essential data files should be stored. If $XDG_CACHE_HOME is either not set or empty, a default equal to $HOME/.cache should be used.

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

> We shouldn’t store anything directly in `$XDG_CACHE_HOME` anyway, rather `$XDG_CACHE_HOME/filecoin-station`, so with the fallback that would be `~/.cache/filecoin-station`

**Comment by mulles** [comment]
When will the fix be released?  I am aeger to run the app :) But somehow I am unable to set the variable $XDG_CACHE_HOME manually.
Or do you have any guide to manually build the app?

**Comment by juliangruber** [comment]
Filecoin Station 0.4.0 is out now 🙌 

https://github.com/filecoin-project/filecoin-station/releases/tag/v0.4.0
