### ISSUE TITLE
Consent with telemetry & error reporting

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#118]
- [ ] Smallprint on the website before download
- [x] A new screen in the app - see #70
 
Things for which want to obtain user's consent:

  -  [x] Usage analytics #80  #160
  -  [x] Telemetry #79 
  -  [x] UI error monitoring #78 #160

**Comment by juliangruber** [comment]
Removed from the milestone, as the current consent screen already covers telemetry, and the website is outside this milestone

**Comment by bajtos** [comment]
Should we perhaps close this issue as done and open two follow-up issues - one for the website and another for the telemetry?

**Comment by juliangruber** [comment]
Telemetry already is covered by issues, I'll share with Onda that we have this website requirement. I'm not sure yet where issues for the website will be tracked. I think we can close this then!
