### ISSUE TITLE
Tailor Saturn Dashboard UI to Station needs

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#46]
Currently, the Saturn module is showing the same UI as https://dashboard.strn.network. This is a good start but far from ideal. 

The public web dashboard is designed to allow the user to enter a FIL address, and the data is fetched from an AWS API endpoint.

The dashboard only shows data from the orchestrator (?); it does not show local/machine-specific data like the current upload/download bandwidth.

We should rethink how should the Dashboard look for a local Saturn node & the Station and implement the required changes.

**Comment by bajtos** [comment]
See https://github.com/filecoin-project/saturn-webui/issues/5

**Comment by juliangruber** [comment]
I was wondering if the two dashboards should even be the same project, it will make Station more flexible if we have a saturn-station UI project

**Comment by bajtos** [comment]
If the saturn L2 node can ship the same dashboard WebUI used by the Station, then people can run the node without the Station (e.g. on a home router) and still get the nice UI.

**Comment by juliangruber** [comment]
I was thinking, if we have two dashboard projects that reuse the same components but have slightly different configuration, then we still get that while having more flexibility

**Comment by bajtos** [comment]
> I was thinking, if we have two dashboard projects that reuse the same components but have slightly different configuration, then we still get that while having more flexibility

That's a great idea! 

I am a bit reluctant to have two standalone projects/GH repositories, there is a lot of overhead in that.

How about using different routes for different view configurations? 

The website is using `/` and `/address/{FilAddr}` routes. The node is using `/webui`, which currently redirects to `/webui/address/{FilAddr}`. I created this redirect as quick hack to get the dashboard show in the Station, I am happy to rework it.

Maybe we can configure the bundler to create two outputs - one for the website, another for the L2 Node?

**Comment by juliangruber** [comment]
To me it has to be two dashboard projects because it's out of scope for Saturn to maintain the Station dashboard, and I would like to not clutter their notifications and issue tracker with this work.

This is a topic that is coming up frequently (how much separation do we need between Saturn and Station), and I would like to discuss this with the Saturn team to get everyones' needs covered, while also keeping our maintenance cost down of course.

**Comment by gruns** [comment]
>I was thinking, if we have two dashboard projects that reuse the same components but have slightly different configuration, then we still get that while having more flexibility

this is the first thing that came to my mind, too 🙌 

> To me it has to be two dashboard projects because it's out of scope for Saturn to maintain the Station dashboard, and I would like to not clutter their notifications and issue tracker with this work.

to be clear, the dashboard we're talking about is the *saturn* l2 dashboard inside station, right? that is, *not* the station dashboard itself, where one can see the status of all the modules/apps station is running. if the former, that saturn l2 station dashboard is under saturn's roof more than it's under station's roof

> This is a topic that is coming up frequently (how much separation do we need between Saturn and Station)

ya. i still think, strongly, that station and saturn should be tightly integrated for the initial launch. until there's actually multiple compelling modules to run, it doesn't make sense to dilute the product and confuse the ui and user

**Comment by juliangruber** [comment]
> to be clear, the dashboard we're talking about is the _saturn_ l2 dashboard inside station, right? that is, _not_ the station dashboard itself, where one can see the status of all the modules/apps station is running. if the former, that saturn l2 station dashboard is under saturn's roof more than it's under station's roof

This is correct! I don't understand you sentence "if the former, ..." in this context 😅

**Comment by bajtos** [comment]
As part of our recent pivot, we decided that Station should provide a station-wide dashboard. We don't intend to provide module-level dashboards in the foreseeable future.

I am closing this task as "not planned".
