### ISSUE TITLE
Integrate Saturn L2 v0.0.8 and configure ROOT_DIR

### ISSUE THREAD

**Issue by juliangruber** [filecoin-project/filecoin-station#56]
Once a new release is cut https://github.com/filecoin-project/saturn-l2

**Comment by bajtos** [comment]
As part of this work, I'd like us to configure the new `ROOT_DIR` env var accepted by Saturn L2. This variable controls the location where the L2 node keeps the cache.

We must choose the right location for this cache:
- `%LOCALAPPDATA%` on Windows
- `XDG_CACHE_HOME` on Linux
- `~/Library/Caches/` on macOS

See https://github.com/ipfs/ipfs-desktop/issues/1656, https://github.com/electron/electron/issues/8124, https://github.com/electron/electron/issues/1404

**Comment by bajtos** [comment]
In particular, we cannot use Electron's APIs for choosing the cache dir location.

**Comment by bajtos** [comment]
See https://github.com/filecoin-saturn/L2-node/releases/tag/v0.0.7

**Comment by bajtos** [comment]
> In particular, we cannot use Electron's APIs for choosing the cache dir location.

FWIW, here is an Electron PR trying to simplify access to the platform-specific cache/local-app-data directory: https://github.com/electron/electron/pull/34337
