### ISSUE TITLE
Usage analytics

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#80]
We want to record analytics to better understand usage patterns, for example how many people were not able to complete the onboarding flow.

Tasks:
- [x] Setup infrastructure to gather events and visualise them
  - [x] Decide self-hosted vs SaaS
  - [x] Acquire funds
  - [x] Deploy SaaS https://plausible.io/#pricing
- [ ] Modify Station UI to report the following events
  - [ ] a user starts the app (the onboarding flow)
  - [ ] the user closes the app at the screen “Enter FIL”
- [x] Add a new paragraph to the Consent screen to describe what telemetry data is collected. If the consent screen is not implemented yet, then add a new subtask to the appropriate issue. https://github.com/filecoin-project/filecoin-station/issues/118

**Comment by juliangruber** [comment]
> * the user closes the app at the screen “Enter FIL”

maybe more generic: "the user performs a navigation event", which can capture any screen change generically

**Comment by juliangruber** [comment]
> * [ ]  the user closes the app at the screen “Enter FIL”

-> Needs to be able to track exit pages

**Comment by juliangruber** [comment]
After browsing https://sentry.io/welcome/, I think Sentry isn't a good option for this. It's purpose is always error tracking, if usage of Station doesn't lead to an error then it's none of Sentry's concern. That's also why it doesn't have exit page tracking (there is never an error leaving the page), and launching the app isn't tracked either, unless it leads to an error. I know google analytics tracks all of this, but I will first look for other alternatives.

**Comment by juliangruber** [comment]
[Plausible](https://plausible.io/) offers exit pages:

<img width="1044" alt="Screenshot 2022-09-01 at 14 15 58" src="https://user-images.githubusercontent.com/10247/187911609-a1bb0fbc-fadc-4acb-b709-806736daa7e5.png">

It also provides other metrics useful for Station, eg

- Conversions
- Pageviews
- Screen Size
- Visit Duration

Having used Plausible before, I think it will work for us, but I want to do some further research.

**Comment by juliangruber** [comment]
[IPFS Desktop](https://github.com/ipfs/ipfs-desktop) uses [Countly](https://count.ly/), which offers a free and self-hosted version as well. I _think_ it offers more features than Plausible, but also looks somewhat more outdated. We would like have to self-host this, as they only offer an enterprise hosted plan.

**Comment by bajtos** [comment]
I have good experience with Plausible too 👍🏻 

I vaguely remember @patrickwoodhead mentioning some issues with Countly and that perhaps we should look into other options, but I don't recall any details 😞

**Comment by hacdias** [comment]
@juliangruber there are currently some [bugs](https://github.com/ipfs/ipfs-desktop/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+countly+) in our implementation in IPFS Desktop + Web UI. Furthermore, we (I?) haven't been using the statistics actively, so it's hard to recommend it or not.

**Comment by juliangruber** [comment]
@hacdias thank you for providing context! 🙏 
@patrickwoodhead  if we go with Plausible, do you think we should go with SaaS which means less work for us, or self hosted, which means more privacy (or first the former than the latter?)

**Comment by juliangruber** [comment]
also @patrickwoodhead, since you apparently had some issues with Countly, could you check whether Plausible answers your questions better?

**Comment by patrickwoodhead** [comment]
@bajtos @juliangruber, I didn't have any issues with Countly. It is just that the maintanier of the IPFS Countly account stopped maintaining it and so I think some teams moved off it. We can use Countly or Plausible.
