### ISSUE TITLE
Expose stats & events from L2-node to WebUI

### ISSUE THREAD

**Issue by bajtos** [filecoin-project/filecoin-station#81]
Station backend needs to expose the following stats & events for the WebUI:

## Stats

Stats are persisted by L2 Node, we just need to call HTTP API to get the new numbers.

- [x] Number of jobs served
  - We should periodically call L2-node's HTTP endpoint `/stats` and parse the number from there, see https://github.com/filecoin-saturn/L2-node/pull/59

👉🏻 Done in https://github.com/filecoin-project/filecoin-station/pull/136

## Activity feed 

Activity is reported via events, we need to persist them on our side.
- [x] Implement persistence for activity feed. Keep X latest entries only and delete old ones.

Record the following events
- [x] Saturn L2 Node started
- [x] Saturn L2 Node exited or panicked (include the panic message?)
- [x] Any lines from L2-node's stdout stream that are prefixed with `INFO`

👉🏻 Done in https://github.com/filecoin-project/filecoin-station/pull/110

## IPC integration

Ideally, we should have two APIs for WebUI:

1. Get the initial state (# of jobs served, activity log)
2. Subscribe to events to get notified when a new activity is reported or more jobs were finished

**Comment by juliangruber** [comment]
> [ ] Implement persistence for activity feed. Keep X latest entries only and delete old ones.

Do you have an idea how to implement this? For now we could just keep state as an array and flush to disk as JSON when there is an update, debounced every second?

**Comment by juliangruber** [comment]
I think that works!
